### ISSUE TITLE
[Suggestion] Support for other date formats when a date is selected

### ISSUE THREAD

**Issue by Coreusa** [ridewn/vue-date-picker#3]
Right now, it seems to be hard coded that the date returned is always in the form of Y-M-D (without leading zeroes).

` return ${this.selectedYear}-${this.selectedMonth + 1}-${this.selectedDay + 1}`

Which could yield: 2017-9-1

It would be nice to support other output formats when a date is selected, for instance DD.MM.YYYY (which in this example would yield 01.09.2017)

**Comment by trevorstacy** [comment]
Hi Sobient,

this issue is similar to issue #1. I've since added support for formatting the date picker's emitted date. I have also added it in the readme, although it is at the bottom so you may not have seen it. I'll add a table of contents so people will know that there is an option to format the dates.

Anyway, as the readme says, all you need to do is add a `:format` prop that takes a reference to a function. This function receives the date picker's date, and may format it however you like. When the input event is emitted, the date pickers's date value will be run through the function.

> To format the date picker's value, you may use the :format prop. The format prop takes a reference to a function; this function receives the date picker's date value (e.g. 2016-4-19), and formats it however you wish
> 
> ```
> <date-picker :format="formatDate"
>              @close="show = false"
>              v-if="show"
>              v-model="date"></date-picker>
> ```
> In your component's methods...
> 
> ```
> formatDate (date) {
>   return moment(date).format('LL')
> }
> ```
> In the above example, if a user selected "2017-8-29" as the date, the date value would be "August 29, 2017".

**Comment by Coreusa** [comment]
@ridewn I've seen it, but it doesn't change the fact that the original emitted value from DatePicker isn't a conformable date in for instance IE11 (creating a new Date object requires the date to be with slashes / instead of dash - ). I had to replace the returned value from vue-date-picker and then create a date object out of it. 

So, as I originally stated, vue-date-picker doesn't have the option to change the format of the selected date it emits. 

Here's a package that basically does all the heavy lifting for you, and should be easy to implement into vue-date-picker: https://www.npmjs.com/package/date-and-time
