### ISSUE TITLE
Timepicker support

### ISSUE THREAD

**Issue by theKhorshed** [ridewn/vue-date-picker#8]
Really great works!

I'm using this on one of my projects. I also need a similar style time-picker.

Does it have support for time picker? If not I believe it would be a nice addition.

Thanks

**Comment by trevorstacy** [comment]
Thank you.

It does not include a time picker because time pickers are actually a separate picker component:  https://material.io/guidelines/components/pickers.html#pickers-time-pickers

I've thought about making a time picker component with Vue before, but don't really need one for the application I'm working on. Sorry! If you're really invested in material design you should check out http://vuematerial.io/.
